version: '3.9'
services:
  denuncias:
    build: ./microservicio_denuncias_RN
    ports:
      - "8081:8080"

  reserva:
    build: ./microservicio_reserva_RN
    ports:
      - "8082:8080"

  reviews:
    build: ./microservicio_reviews_RN
    ports:
      - "8083:8080"

  usuario:
    build: ./microservicio_usuario_RN
    ports:
      - "8084:8080"

  viajes:
    build: ./microservicio_viajes_RN
    ports:
      - "8085:8080"